version: "3.12"

services:
  python:
    container_name: api_server
    build: .
    image: chsyu/fastapi2023:1.1
    command: python app.py
    ports:
      - "5001:5000" 
    volumes:
      - .:/code